#!/usr/bin/env python3
"""Generate and check the RDF/Turtle profile from docs/profile.jsonld.

The JSON-LD profile remains the canonical structured source. This script derives
`docs/profile.ttl` from it so the Turtle serialization stays synchronized without
introducing an additional hand-maintained identity file.
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_JSONLD = REPO_ROOT / "docs" / "profile.jsonld"
DEFAULT_TTL = REPO_ROOT / "docs" / "profile.ttl"


def _as_list(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def _types(node: dict[str, Any]) -> set[str]:
    return {str(item) for item in _as_list(node.get("@type"))}


def _literal(value: Any) -> str:
    text = str(value)
    text = text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{text}"'


def _iri(value: str) -> str:
    return f"<{value}>"


def _date_literal(value: str) -> str:
    date_value = value.split("T", 1)[0]
    return f'{_literal(date_value)}^^xsd:date'


def _find_node(graph: list[dict[str, Any]], node_type: str) -> dict[str, Any]:
    for node in graph:
        if node_type in _types(node):
            return node
    raise ValueError(f"Could not find {node_type!r} node in JSON-LD graph")


def _emit_literal_list(lines: list[str], predicate: str, values: list[Any], terminator: str = ";") -> None:
    if not values:
        return
    lines.append(f"    {predicate}")
    for index, value in enumerate(values):
        end = terminator if index == len(values) - 1 else ","
        lines.append(f"        {_literal(value)}{end}")


def _emit_iri_list(lines: list[str], predicate: str, values: list[str], terminator: str = ";") -> None:
    if not values:
        return
    lines.append(f"    {predicate}")
    for index, value in enumerate(values):
        end = terminator if index == len(values) - 1 else ","
        lines.append(f"        {_iri(value)}{end}")


def _emit_identifier_list(lines: list[str], identifiers: list[dict[str, Any]], terminator: str = ";") -> None:
    if not identifiers:
        return
    lines.append("    schema:identifier")
    for index, item in enumerate(identifiers):
        end = terminator if index == len(identifiers) - 1 else ","
        lines.extend(
            [
                "        [",
                "            a schema:PropertyValue ;",
                f"            schema:propertyID {_literal(item['propertyID'])} ;",
                f"            schema:value {_literal(item['value'])} ;",
                f"            schema:url {_iri(item['url'])}",
                f"        ]{end}",
            ]
        )


def _node_ref(value: dict[str, Any] | str) -> str:
    if isinstance(value, dict) and "@id" in value:
        return str(value["@id"])
    if isinstance(value, str):
        return value
    raise ValueError(f"Unsupported node reference: {value!r}")


def _schema_type_list(node: dict[str, Any]) -> str:
    return ", ".join(f"schema:{str(node_type)}" for node_type in _as_list(node.get("@type")))


def _emit_web_page(lines: list[str], page: dict[str, Any]) -> None:
    lines.extend(
        [
            f"{_iri(page['@id'])}",
            f"    a {_schema_type_list(page)} ;",
            f"    schema:url {_iri(page['url'])} ;",
            f"    schema:name {_literal(page['name'])} ;",
            f"    schema:description {_literal(page['description'])} ;",
            f"    schema:inLanguage {_literal(page.get('inLanguage', 'en'))} ;",
            f"    schema:isPartOf {_iri(_node_ref(page['isPartOf']))} ;",
            f"    schema:about {_iri(_node_ref(page['about']))} .",
            "",
        ]
    )


def generate_ttl(jsonld_path: Path = DEFAULT_JSONLD) -> str:
    data = json.loads(jsonld_path.read_text(encoding="utf-8"))
    graph = data.get("@graph", [])
    if not isinstance(graph, list):
        raise ValueError("JSON-LD profile must contain an @graph list")

    website = _find_node(graph, "WebSite")
    profile_page = _find_node(graph, "ProfilePage")
    person = _find_node(graph, "Person")

    person_id = person["@id"]
    profile_doc_id = "https://pedropaulofb.github.io/profile.ttl"
    jsonld_doc_id = "https://pedropaulofb.github.io/profile.jsonld"

    lines: list[str] = [
        "# Generated from docs/profile.jsonld by scripts/generate_profile_ttl.py.",
        "# Do not edit this file manually; update docs/profile.jsonld and regenerate.",
        "",
        "@prefix dcterms: <http://purl.org/dc/terms/> .",
        "@prefix foaf: <http://xmlns.com/foaf/0.1/> .",
        "@prefix schema: <https://schema.org/> .",
        "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
        "",
        f"{_iri(profile_doc_id)}",
        "    a schema:DigitalDocument, foaf:PersonalProfileDocument ;",
        f"    dcterms:creator {_iri(person_id)} ;",
        f"    dcterms:created {_date_literal(profile_page['dateCreated'])} ;",
        f"    dcterms:language {_literal(profile_page.get('inLanguage', website.get('inLanguage', 'en')))} ;",
        f"    dcterms:title {_literal('Machine-readable Turtle profile for ' + person['name'])} ;",
        f"    foaf:primaryTopic {_iri(person_id)} ;",
        f"    schema:about {_iri(person_id)} ;",
        f"    schema:encodingFormat {_literal('text/turtle')} ;",
        f"    schema:isBasedOn {_iri(jsonld_doc_id)} ;",
        f"    schema:mainEntity {_iri(person_id)} .",
        "",
        f"{_iri(person_id)}",
        "    a schema:Person, foaf:Person ;",
        f"    schema:name {_literal(person['name'])} ;",
        f"    foaf:name {_literal(person['name'])} ;",
        f"    schema:givenName {_literal(person['givenName'])} ;",
        f"    schema:familyName {_literal(person['familyName'])} ;",
    ]

    _emit_literal_list(lines, "schema:alternateName", _as_list(person.get("alternateName")))
    lines.extend(
        [
            f"    schema:jobTitle {_literal(person['jobTitle'])} ;",
            f"    schema:description {_literal(person['description'])} ;",
            f"    schema:url {_iri(person['url'])} ;",
            f"    schema:mainEntityOfPage {_iri(_node_ref(person['mainEntityOfPage']))} ;",
            "    schema:worksFor [",
            "        a schema:Organization ;",
            f"        schema:name {_literal(person['worksFor']['name'])} ;",
            f"        schema:url {_iri(person['worksFor']['url'])}",
            "    ] ;",
            "    schema:workLocation [",
            "        a schema:Place ;",
            f"        schema:name {_literal(person['workLocation']['name'])}",
            "    ] ;",
        ]
    )

    _emit_iri_list(lines, "schema:sameAs", [str(value) for value in _as_list(person.get("sameAs"))])
    _emit_identifier_list(lines, [item for item in _as_list(person.get("identifier")) if isinstance(item, dict)])
    _emit_literal_list(lines, "schema:knowsAbout", _as_list(person.get("knowsAbout")))
    _emit_literal_list(lines, "schema:skills", _as_list(person.get("skills")))
    _emit_iri_list(lines, "schema:subjectOf", [_node_ref(item) for item in _as_list(person.get("subjectOf"))], terminator=".")

    lines.extend(
        [
            "",
            f"{_iri(website['@id'])}",
            "    a schema:WebSite ;",
            f"    schema:name {_literal(website['name'])} ;",
            f"    schema:url {_iri(website['url'])} ;",
            f"    schema:inLanguage {_literal(website.get('inLanguage', 'en'))} ;",
            f"    schema:author {_iri(_node_ref(website['author']))} ;",
            f"    schema:publisher {_iri(_node_ref(website['publisher']))} ;",
            f"    schema:about {_iri(_node_ref(website['about']))} ;",
        ]
    )
    _emit_iri_list(lines, "schema:hasPart", [_node_ref(item) for item in _as_list(website.get("hasPart"))], terminator=".")

    lines.extend(
        [
            "",
            f"{_iri(profile_page['@id'])}",
            "    a schema:ProfilePage ;",
            f"    schema:url {_iri(profile_page['url'])} ;",
            f"    schema:name {_literal(profile_page['name'])} ;",
            f"    schema:description {_literal(profile_page['description'])} ;",
            f"    schema:inLanguage {_literal(profile_page.get('inLanguage', 'en'))} ;",
            f"    schema:isPartOf {_iri(_node_ref(profile_page['isPartOf']))} ;",
            f"    schema:mainEntity {_iri(_node_ref(profile_page['mainEntity']))} ;",
            f"    schema:about {_iri(_node_ref(profile_page['about']))} ;",
            f"    schema:author {_iri(_node_ref(profile_page['author']))} .",
            "",
        ]
    )

    for node in graph:
        if node.get("@id") in {website["@id"], profile_page["@id"], person["@id"]}:
            continue
        if _types(node) & {"WebPage", "ContactPage"}:
            _emit_web_page(lines, node)

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--jsonld", type=Path, default=DEFAULT_JSONLD, help="Path to the source JSON-LD profile")
    parser.add_argument("--ttl", type=Path, default=DEFAULT_TTL, help="Path to the generated Turtle profile")
    parser.add_argument("--check", action="store_true", help="Fail if the Turtle file is not up to date")
    args = parser.parse_args()

    expected = generate_ttl(args.jsonld)

    if args.check:
        if not args.ttl.exists():
            print(f"Missing generated Turtle file: {args.ttl}", file=sys.stderr)
            return 1
        current = args.ttl.read_text(encoding="utf-8")
        if current != expected:
            diff = difflib.unified_diff(
                current.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=str(args.ttl),
                tofile="generated profile.ttl",
            )
            sys.stderr.writelines(diff)
            return 1
        print(f"{args.ttl} is up to date")
        return 0

    args.ttl.write_text(expected, encoding="utf-8")
    print(f"Wrote {args.ttl}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
